INSERT INTO SHOW_SETUP (SHOW_NO, ROW_PER_SHOW, ROW_PER_SEAT, CNCL_WD_MIN, CREATED_DT, VERSION)
values ('1', 1, 10, 2,CURRENT_TIMESTAMP,1);

INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (1, '1', 'A1', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (2, '1', 'A2', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (3, '1', 'A3', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (4, '1', 'A4', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (5, '1', 'A5', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (6, '1', 'A6', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (7, '1', 'A7', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (8, '1', 'A8', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (9, '1', 'A9', 1);
INSERT INTO SHOW_SEAT(SEAT_ID, SHOW_NO, SEAT_NO, VERSION) VALUES (10, '1', 'A10', 1);

INSERT INTO BOOKING(BOOK_NO, PHONE_NO, SHOW_NO, BOOKED_DT, VERSION)
VALUES ('07c7a111-4360-4e2a-940a-1ddda8f1f5a5', '123', '1', CURRENT_TIMESTAMP, 1);

INSERT INTO TICKET(ID, TICKET_NO, BOOK_NO, SEAT_ID, CANCELLED_DT, VERSION)
VALUES (1, '123456', '07c7a111-4360-4e2a-940a-1ddda8f1f5a5', 1, NULL, 1);
INSERT INTO TICKET(ID, TICKET_NO, BOOK_NO, SEAT_ID, CANCELLED_DT, VERSION)
VALUES (2, '123457', '07c7a111-4360-4e2a-940a-1ddda8f1f5a5', 2, CURRENT_TIMESTAMP , 1);